services:
  mysql:
    image: mysql:8
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
