services:
  postgres:
    container_name: postgres12
    image: postgres:12
    ports:
      - "5434:5432"  # Exposing port 5434
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres12_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres12_network

networks:
  postgres12_network:
    name: postgres12_network
    driver: bridge
