services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"  # Exposing port 27018
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: unless-stopped
